# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='qty',
        ),
    ]
