# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_job_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lineno',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='color',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='lotno',
            field=models.CharField(default='', max_length=32),
        ),
    ]
