# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20170812_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='finish_date',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='start_date',
            new_name='start',
        ),
    ]
