# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20170812_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='color',
            new_name='colorname',
        ),
    ]
