# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:49
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20170817_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
